### ISSUE TITLE
Installation with kubectl failes

### ISSUE THREAD

**Issue by driehle** [costela/hcloud-ip-floater#1]
Hi,

when trying to install as described in you Readme file with
```
echo "namespace: hcloud-ip-floater
 bases:
   - github.com/costela/hcloud-ip-floater/deploy?ref=v0.1.4
 secretGenerator:
   - name: hcloud-ip-floater-secret-env
     literals:
       - HCLOUD_IP_FLOATER_HCLOUD_TOKEN=...." > fip.yml
kubectl apply -f fip.yml
```

I get the following error:
```
error: error validating "test.yml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```

Any ideas how to fix this?
